# Generated by Django 4.0.3 on 2022-04-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, verbose_name='年份')),
                ('month', models.CharField(max_length=100, verbose_name='月份')),
                ('attendance_day', models.CharField(max_length=100, verbose_name='出勤天数')),
                ('base_pay', models.CharField(max_length=100, verbose_name='基本工资')),
                ('post_way', models.CharField(max_length=100, verbose_name='岗位工资')),
                ('merit_pay', models.CharField(max_length=100, verbose_name='绩效工资')),
                ('benefit_bonus', models.CharField(max_length=100, verbose_name='效益奖')),
                ('seniority_pay', models.CharField(max_length=100, verbose_name='工龄工资')),
                ('overtime_wage', models.CharField(max_length=100, verbose_name='加班工资')),
                ('wage_subtotal', models.CharField(max_length=100, verbose_name='工资小计')),
                ('meal_subsidy', models.CharField(max_length=100, verbose_name='餐费补贴')),
                ('high_temperature_subsidy', models.CharField(max_length=100, verbose_name='高温补贴')),
                ('housing_allowance', models.CharField(max_length=100, verbose_name='住房补贴')),
                ('traffic_subsidy', models.CharField(max_length=100, verbose_name='交通补贴')),
                ('health_care_subsidy', models.CharField(max_length=100, verbose_name='保健补贴')),
                ('middle_night_subsidy', models.CharField(max_length=100, verbose_name='中晚班津贴')),
                ('scarce_specialty_subsidy', models.CharField(max_length=100, verbose_name='稀缺专业补贴')),
                ('subsidy_subtotal', models.CharField(max_length=100, verbose_name='补贴小计')),
                ('meals_deduction', models.CharField(max_length=100, verbose_name='餐费扣款')),
                ('rent_deduction', models.CharField(max_length=100, verbose_name='房租扣款')),
                ('water_electricity_deduction', models.CharField(max_length=100, verbose_name='水电扣款')),
                ('sunshine_due', models.CharField(max_length=100, verbose_name='阳光会费')),
                ('social_security', models.CharField(max_length=100, verbose_name='社保扣款')),
                ('accumulation_fund', models.CharField(max_length=100, verbose_name='公积金')),
                ('income_tax', models.CharField(max_length=100, verbose_name='所得税')),
                ('deduction_subtotal', models.CharField(max_length=100, verbose_name='扣款小计')),
                ('net_pay', models.CharField(max_length=100, verbose_name='应发工资')),
                ('net_payroll', models.CharField(max_length=100, verbose_name='实发工资')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
